export interface CategorySeoData {
  name: string;
  gujaratiName: string;
  gujaratiName2?: string;
  slug: string;
  shortDesc: string;
  longDesc: string;
  gujaratiDesc: string;
  keywords: string[];
  gujaratiKeywords: string[];
  exams: string[];
  faqs: { q: string; a: string }[];
  relatedCategories: string[];
  color: string;
  emoji: string;
}

export const CATEGORY_SEO: Record<string, CategorySeoData> = {
  'Agriculture': {
    name: 'Agriculture', gujaratiName: 'કૃષિ', gujaratiName2: 'ખેતી', slug: 'Agriculture',
    shortDesc: 'Agriculture Current Affairs MCQs in Gujarati for GPSC, GSSSB & CCE 2026.',
    longDesc: 'Agriculture current affairs cover government schemes like PM-KISAN, crop production records, fertilizer policy, irrigation projects, and agri-technology. These questions appear in GSSSB CCE, GPSC Class 1-2, and Talati exams. Practice 100+ MCQs with explanations in Gujarati.',
    gujaratiDesc: 'ખેતી સંબંધિત કરંટ અફેર્સ — સરકારી યોજनाઓ, પાક ઉત્પાદન, ખેડૂત કલ્યાણ, સિંચાઈ, અને કૃષિ ટેક્નોલોજી. GPSC, GSSSB CCE, તલાટી અને PSI પરીક્ષા માટે ઉપયોગી.',
    keywords: ['Agriculture Current Affairs 2026', 'Agriculture Current Affairs in Gujarati', 'Krushi Current Affairs Gujarati', 'Agriculture MCQ GPSC', 'Agriculture Quiz GSSSB', 'Agriculture Current Affairs Gujarat', 'PM-KISAN Gujarat', 'Farming Current Affairs India'],
    gujaratiKeywords: ['ખેતી કરંટ અફેર્સ', 'કૃષિ કરંટ અફેર ૨૦૨૬', 'ખેડૂત કલ્યાણ ક્વિઝ', 'ખેતી MCQ ગુજરાતી'],
    exams: ['GSSSB CCE', 'GPSC Class 1-2', 'Talati Mantri', 'Bin Sachivalay'],
    faqs: [
      { q: 'Agriculture current affairs in Gujarati ક્યાં practice કરી શકાય?', a: 'CurrentAdda પર Agriculture category page પર free MCQs practice કરી શકો. દરરોજ નવા questions add થાય છે.' },
      { q: 'Which exam asks Agriculture current affairs questions?', a: 'GSSSB CCE 2026, GPSC Class 1-2, Talati Mantri, and Bin Sachivalay exams frequently ask Agriculture current affairs.' },
      { q: 'Agriculture current affairs 2026 for Gujarat exam - what topics?', a: 'PM-KISAN, crop MSP, irrigation schemes, agri-export policy, drone in farming, and Gujarat specific agri news are key topics.' },
    ],
    relatedCategories: ['Environment', 'Economy', 'National'],
    color: 'emerald', emoji: '🌾',
  },
  'Art and Culture': {
    name: 'Art and Culture', gujaratiName: 'કળા અને સંસ્કૃતિ', slug: 'Art and Culture',
    shortDesc: 'Art and Culture Current Affairs MCQs in Gujarati for GPSC & GSSSB exams.',
    longDesc: 'Art and Culture questions cover classical dances, folk arts, UNESCO heritage sites, literary awards, Padma awards, Gujarati culture, festivals, and architecture. High-weightage topic in GPSC Mains and GSSSB CCE. Practice all sets with explanations.',
    gujaratiDesc: 'કળા અને સંસ્કૃતિ — ભારતીય શાસ્ત્રીય નૃત્ય, લોકકળા, UNESCO વારસો, સાહિત્ય પુરસ્કાર, ગુજરાતી સંસ્કૃતિ, તહેવારો. GPSC Mains અને GSSSB CCE માટે ઉપયોગી.',
    keywords: ['Art and Culture Current Affairs 2026', 'Art Culture Current Affairs in Gujarati', 'Art Culture MCQ GPSC', 'Indian Culture Quiz Gujarati', 'Art Culture GSSSB', 'Gujarati Culture Current Affairs', 'UNESCO Heritage India 2026'],
    gujaratiKeywords: ['કળા સંસ્કૃતિ કરંટ અફેર્સ', 'ભારતીય સંસ્કૃતિ ક્વિઝ ગુજરાતી', 'કળા MCQ ગુજરાતી ૨૦૨૬'],
    exams: ['GPSC Class 1-2', 'GSSSB CCE', 'Talati Mantri', 'PSI'],
    faqs: [
      { q: 'Art and Culture current affairs in Gujarati ક્યાં practice કરવી?', a: 'CurrentAdda Art and Culture category page પર 100+ MCQs Gujarati explanations સાથે practice કરો.' },
      { q: 'Which dance forms are important for GPSC exam?', a: 'Bharatanatyam, Kathak, Garba, Dandiya, Mohiniyattam, and Kuchipudi are frequently asked in GPSC and GSSSB exams.' },
    ],
    relatedCategories: ['Festivity', 'National', 'Talkies'],
    color: 'rose', emoji: '🎨',
  },
  'Awards and Honours': {
    name: 'Awards and Honours', gujaratiName: 'પુરસ્કાર અને સન્માન', slug: 'Awards and Honours',
    shortDesc: 'Awards and Honours Current Affairs in Gujarati — Padma, Nobel, Oscar, Bharat Ratna.',
    longDesc: 'Awards current affairs include Padma Awards, Nobel Prize, Bharat Ratna, Oscar, Pulitzer, Rajiv Gandhi Khel Ratna, Sahitya Akademi, and international honours. One of the highest-yielding topics in competitive exams. Updated daily.',
    gujaratiDesc: 'પ્રખ્યાત પુરસ્કારો — પદ્મ વિભૂષણ, ભારત રત્ન, નોબેલ, ઓસ્કાર, ખેલ રત્ન, સાહિત્ય અકાડેમી. GPSC, GSSSB, PSI, Constable — બધા exams માટે ઉપયોગી.',
    keywords: ['Awards and Honours Current Affairs 2026', 'Awards Honours Gujarati', 'Padma Awards 2026 Gujarati', 'Nobel Prize 2026 Quiz', 'Awards MCQ GPSC GSSSB', 'Bharat Ratna 2026', 'Oscar 2026 Current Affairs Gujarati'],
    gujaratiKeywords: ['પુરસ્કાર કરંટ અફેર્સ ૨૦૨૬', 'ભારત રત્ન ક્વિઝ', 'પદ્મ પુરસ્કાર ૨૦૨૬ ગુજરાતી'],
    exams: ['GPSC Class 1-2', 'GSSSB CCE', 'PSI', 'Constable', 'Talati'],
    faqs: [
      { q: 'Awards and Honours current affairs Gujarati — ક્યાં practice કરવું?', a: 'CurrentAdda Awards category page પર Padma, Nobel, Oscar, Bharat Ratna MCQs Gujarati explanations સાથે practice કરો.' },
      { q: 'Which awards are most frequently asked in Gujarat exams?', a: 'Padma Awards, Bharat Ratna, Rajiv Gandhi Khel Ratna, and Nobel Prize are most frequently asked in GPSC and GSSSB exams.' },
    ],
    relatedCategories: ['Sports', 'Persons', 'National'],
    color: 'amber', emoji: '🏆',
  },
  'Banking': {
    name: 'Banking', gujaratiName: 'બેન્કિંગ', slug: 'Banking',
    shortDesc: 'Banking Current Affairs in Gujarati — RBI, SBI, SEBI, Repo Rate, Government Banks.',
    longDesc: 'Banking current affairs cover RBI policies, repo rate changes, bank mergers, new banking licences, digital payment update, government banking schemes, SEBI regulations, and financial inclusion. Essential for all Gujarat government exams.',
    gujaratiDesc: 'બેન્કિંગ — RBI પૉલિસી, રેપો રેટ, SBI, SEBI, ડિજિટલ પેમેન્ટ, બેન્ક મર્જર, સરકારી બેન્કિંગ યોજनाઓ. GPSC, GSSSB CCE, Talati, PSI, Constable exams.',
    keywords: ['Banking Current Affairs 2026', 'Banking Current Affairs in Gujarati', 'RBI Current Affairs Gujarati', 'Banking MCQ GPSC', 'SEBI Current Affairs 2026', 'Bank Merger 2026 Quiz', 'Repo Rate 2026 Gujarati'],
    gujaratiKeywords: ['બેન્કિંગ કરંટ અફેર્સ ગુજરાતી', 'RBI ક્વિઝ ગુજરાતી ૨૦૨૬', 'SEBI MCQ ગુજરાતી'],
    exams: ['GPSC Class 1-2', 'GSSSB CCE', 'PSI', 'Constable', 'Bin Sachivalay'],
    faqs: [
      { q: 'Banking current affairs in Gujarati ક્યાં practice કરવું?', a: 'CurrentAdda Banking category page પર RBI, SEBI, SBI MCQs Gujarati explanations સાથે free practice કરો.' },
      { q: 'What banking topics are asked in GSSSB CCE 2026?', a: 'RBI repo rate, bank mergers & acquisitions, digital payments, financial inclusion schemes, and new banking regulations are key topics.' },
    ],
    relatedCategories: ['Economy', 'Finance', 'Business'],
    color: 'blue', emoji: '🏦',
  },
  'Bills and Acts': {
    name: 'Bills and Acts', gujaratiName: 'બિલ અને અધિનિયમ', slug: 'Bills and Acts',
    shortDesc: 'Bills and Acts Current Affairs in Gujarati — Parliament, New Laws, Amendments 2026.',
    longDesc: 'Bills and Acts current affairs cover new Parliament bills, constitutional amendments, landmark Supreme Court judgements, state legislation, and regulatory acts. Very important in GPSC Mains, GSSSB CCE, and PSI exams.',
    gujaratiDesc: 'સંસદ બિલ, બંધારણ સુધારા, સુપ્રીમ કોર્ટ ચુકાદા, નવા અધિનિયમ. GPSC Class 1-2, GSSSB CCE, PSI, Bin Sachivalay exams.',
    keywords: ['Bills and Acts Current Affairs 2026', 'Parliament Bills 2026 Gujarati', 'New Laws India 2026 MCQ', 'Bills Acts GPSC GSSSB', 'Constitutional Amendment 2026 Gujarati', 'Parliament Session Current Affairs'],
    gujaratiKeywords: ['બિલ અધિનિયમ કરંટ અફેર્સ', 'સંસદ બિલ ૨૦૨૬ ગુજરાતી', 'GPSC Bills MCQ ગુજરાતી'],
    exams: ['GPSC Class 1-2', 'GSSSB CCE', 'PSI', 'Bin Sachivalay'],
    faqs: [
      { q: 'Bills and Acts current affairs in Gujarati ક્યાં practice કરવું?', a: 'CurrentAdda Bills and Acts category page પર Parliament bills, constitutional amendments MCQs Gujarati explanations સાથે practice કરો.' },
      { q: 'Which bills are most frequently asked in GPSC exam?', a: 'Major Parliament bills passed in the current session, constitutional amendments, and landmark Supreme Court judgements are most asked.' },
    ],
    relatedCategories: ['Politics', 'National', 'Economy'],
    color: 'slate', emoji: '📜',
  },
  'Business': {
    name: 'Business', gujaratiName: 'વ્યવસાય', gujaratiName2: 'બિઝનેસ', slug: 'Business',
    shortDesc: 'Business Current Affairs in Gujarati — Startups, Corporate, Mergers & Acquisitions 2026.',
    longDesc: 'Business current affairs cover Indian and global corporate news, startup unicorns, FDI, IPO launches, company mergers, CEO appointments, and India\'s business rankings. Tested in GPSC and GSSSB CCE exams.',
    gujaratiDesc: 'ભારત અને વૈશ્વિક કોર્પોરેટ સમાચાર, સ્ટાર્ટઅપ, FDI, IPO, મર્જર, CEO નિમણૂક. GPSC, GSSSB CCE, PSI exams.',
    keywords: ['Business Current Affairs 2026', 'Business Current Affairs in Gujarati', 'Startup Unicorn India 2026', 'Business MCQ GPSC', 'Corporate News Gujarati', 'FDI India 2026 Gujarati', 'IPO 2026 Current Affairs'],
    gujaratiKeywords: ['વ્યવસાય કરંટ અફેર્સ', 'બિઝનેસ ક્વિઝ ગુજરાતી ૨૦૨૬', 'સ્ટાર્ટઅપ MCQ ગુજરાતી'],
    exams: ['GPSC Class 1-2', 'GSSSB CCE', 'PSI'],
    faqs: [
      { q: 'Business current affairs in Gujarati ક્યાં practice કરવું?', a: 'CurrentAdda Business category page પર Startup, FDI, IPO MCQs Gujarati explanations સાથે practice કરો.' },
      { q: 'What business topics come in GSSSB CCE exams?', a: 'Startup unicorns, major company mergers, new IPOs, FDI policy changes, and CEO appointments are frequently asked.' },
    ],
    relatedCategories: ['Economy', 'Banking', 'Finance'],
    color: 'indigo', emoji: '💼',
  },
  'Defence': {
    name: 'Defence', gujaratiName: 'સંરક્ષણ', slug: 'Defence',
    shortDesc: 'Defence Current Affairs in Gujarati — Indian Army, Navy, Air Force, Missiles 2026.',
    longDesc: 'Defence current affairs include Operation names, new weapon systems, missile tests, defence exercises, DRDO achievements, military satellites, and army appointments. Critical topic for PSI, Constable, and GPSC exams.',
    gujaratiDesc: 'ભારતીય સેના, નૌકાદળ, વાયુ સેના, ક્ષેપણાસ્ત્ર, DRDO. PSI, Constable, GPSC, GSSSB CCE exams.',
    keywords: ['Defence Current Affairs 2026', 'Defence Current Affairs in Gujarati', 'Indian Army MCQ Gujarati', 'Defence Quiz GPSC PSI', 'DRDO 2026 Current Affairs', 'Indian Military 2026 Gujarati', 'Missile Test 2026 Quiz'],
    gujaratiKeywords: ['સંરક્ષણ કરંટ અફેર્સ', 'ભારતીય સેના ક્વિઝ ગુજરાતી', 'DRDO MCQ ૨૦૨૬'],
    exams: ['GPSC Class 1-2', 'GSSSB CCE', 'PSI', 'Constable Bharti'],
    faqs: [
      { q: 'Defence current affairs in Gujarati ક્યાં practice કરવું?', a: 'CurrentAdda Defence category page પر Indian Army, Navy, Air Force MCQs Gujarati explanations સाथे practice करो.' },
      { q: 'Which defence topics are important for PSI exam 2026?', a: 'Military exercises, new weapon systems, DRDO achievements, defence deals, and army chief appointments are key topics for PSI exam.' },
    ],
    relatedCategories: ['National', 'International', 'Science'],
    color: 'red', emoji: '🛡️',
  },
  'Economy': {
    name: 'Economy', gujaratiName: 'અર્થતંત્ર', gujaratiName2: 'ઇકોનોમી', slug: 'Economy',
    shortDesc: 'Economy Current Affairs in Gujarati — GDP, Budget, Inflation, Modi Schemes 2026.',
    longDesc: 'Economy current affairs are the highest-weightage topic in GPSC & GSSSB CCE exams. Topics include India\'s GDP growth, Union Budget, inflation data, RBI monetary policy, government economic schemes, GST updates, India\'s world rankings in economy, FDI data, and unemployment rate. Practice 200+ Economy MCQs in Gujarati with detailed explanations for all competitive exams.',
    gujaratiDesc: 'ભારત GDP, કેન્દ્રીય બજેટ, ફુગ!avão, RBI નીতિ, GST, સરકારી આર્થિક યોજnao. GPSC, GSSSB CCE, PSI, Talati, Constable Bharti exams. ૨૦૦+ ઇકોનોમી MCQs Gujarati explanations સાથે.',
    keywords: [
      'Economy Current Affairs 2026', 'Economy Current Affairs in Gujarati',
      'Economy Current Affairs Gujarat', 'Indian Economy MCQ Gujarati',
      'Economy Quiz GPSC', 'Economy MCQ GSSSB CCE', 'GDP India 2026 Gujarati',
      'Union Budget 2026 Current Affairs', 'Economy Current Affairs for PSI',
      'Inflation 2026 India Gujarati Quiz', 'GST Current Affairs 2026 Gujarati',
    ],
    gujaratiKeywords: [
      'અર્થતંત્ર કરંટ અફેર્સ', 'ઇકોનોમી ક્વિઝ ગુજરાતી ૨૦૨૬',
      'અર્થશાસ્ત્ર કરંટ અફેર ૨૦૨૬', 'GDP MCQ ગુજરાતી',
      'ભારતીય અર્થતંત્ર ક્વિઝ', 'ઇકોનોમી MCQ GPSC GSSSB',
    ],
    exams: ['GPSC Class 1-2', 'GSSSB CCE', 'PSI', 'Talati', 'Constable', 'Bin Sachivalay'],
    faqs: [
      { q: 'Economy current affairs in Gujarati ક્યાં practice કરવું?', a: 'CurrentAdda Economy category page पर 200+ MCQs Gujarati explanations साथे free practice करो. GDP, Budget, RBI, GST topics cover थाय छे.' },
      { q: 'Economy current affairs 2026 — GSSSB CCE exam mates kaeva topics important che?', a: 'GDP growth rate, Union Budget highlights, RBI monetary policy, GST changes, India FDI data, unemployment rate, and government schemes are most asked in GSSSB CCE 2026.' },
      { q: 'Economy current affairs in Gujarati — GPSC exam mate?', a: 'GPSC Class 1-2 exam maa Economy current affairs baab GDP, fiscal deficit, inflation, economic survey, and economic reforms par questions avta hoy che.' },
      { q: 'અર્થતંત્ર MCQ Gujarati ક્યાં મળે?', a: 'CurrentAdda.vercel.app Economy category page par badha MCQs Gujarati explanations sathe free malashe.' },
    ],
    relatedCategories: ['Banking', 'Finance', 'Business', 'National'],
    color: 'cyan', emoji: '📈',
  },
  'Education': {
    name: 'Education', gujaratiName: 'શિક્ષણ', slug: 'Education',
    shortDesc: 'Education Current Affairs in Gujarati — NEP, IIT, University Rankings, NEET 2026.',
    longDesc: 'Education current affairs cover National Education Policy (NEP), IIT/IIM/NIT developments, university world rankings, NEET-UG/JEE results, new educational schemes, literacy rates, and Gujarat education news. Practice Education MCQs in Gujarati for GPSC and GSSSB CCE.',
    gujaratiDesc: 'NEP 2020, IIT/IIM/NIT, University Rankings, NEET, JEE, Gujarat Education. GPSC, GSSSB CCE, Talati, PSI exams.',
    keywords: ['Education Current Affairs 2026', 'Education Current Affairs in Gujarati', 'NEP 2026 Gujarati Quiz', 'Education MCQ GPSC GSSSB', 'IIT IIM Current Affairs', 'University Ranking 2026 Quiz', 'NEET JEE Current Affairs'],
    gujaratiKeywords: ['શિક્ષણ કરંટ અફેર્સ', 'NEP MCQ ગુજરાતી', 'Education ક્વિઝ ગુજરાતી ૨૦૨૬'],
    exams: ['GPSC Class 1-2', 'GSSSB CCE', 'Talati', 'PSI'],
    faqs: [
      { q: 'Education current affairs in Gujarati ક્યાં practice કરવું?', a: 'CurrentAdda Education category page par NEP, IIT, University MCQs Gujarati explanations sathe practice karo.' },
      { q: 'Which education topics are asked in GPSC exam?', a: 'NEP, IIT rankings, new universities, literacy programs, and Gujarat education schemes are frequently asked in GPSC and GSSSB exams.' },
    ],
    relatedCategories: ['National', 'Science', 'Technology'],
    color: 'orange', emoji: '🎓',
  },
  'Environment': {
    name: 'Environment', gujaratiName: 'પર્યાવરણ', slug: 'Environment',
    shortDesc: 'Environment Current Affairs in Gujarati — Climate, COP, Wildlife, Green Energy 2026.',
    longDesc: 'Environment current affairs include COP climate summits, pollution index, wildlife conservation news, national parks, renewable energy milestones, and India\'s climate commitments. Essential for GPSC and GSSSB CCE exams.',
    gujaratiDesc: 'COP Summit, Climate Change, Wildlife Conservation, National Parks, Green Energy, Pollution Index. GPSC, GSSSB CCE, Talati, PSI exams.',
    keywords: ['Environment Current Affairs 2026', 'Environment Current Affairs in Gujarati', 'Climate Change MCQ Gujarati', 'Environment Quiz GPSC', 'Wildlife Conservation 2026 Gujarati', 'COP 2026 Current Affairs', 'Green Energy India 2026'],
    gujaratiKeywords: ['પર્યાવરણ કરંટ અફેર્સ', 'Climate Change MCQ ગુજરાતી', 'Environment ક્વિઝ ૨૦૨૬'],
    exams: ['GPSC Class 1-2', 'GSSSB CCE', 'PSI', 'Talati'],
    faqs: [
      { q: 'Environment current affairs in Gujarati ક્યાં practice કરવું?', a: 'CurrentAdda Environment category page par COP, Wildlife, Climate MCQs Gujarati explanations sathe practice karo.' },
      { q: 'Which environment topics come in GPSC exam?', a: 'COP summits, national parks, endangered species, renewable energy, and India\'s emission targets are key environment topics in GPSC.' },
    ],
    relatedCategories: ['Agriculture', 'Science', 'National'],
    color: 'green', emoji: '🌿',
  },
  'Festivity': {
    name: 'Festivity', gujaratiName: 'તહેવાર', slug: 'Festivity',
    shortDesc: 'Festivity Current Affairs in Gujarati — Indian Festivals, Celebrations, Events 2026.',
    longDesc: 'Festivity current affairs include national and state celebrations, cultural events, important days observed, theme-based events, and international celebrations. Useful for all Gujarat government competitive exams.',
    gujaratiDesc: 'ભારત-ગુજરાત તહેવારો, રાષ્ટ્રીય ઉજવણી, International Events. GPSC, GSSSB CCE, PSI, Constable, Talati exams.',
    keywords: ['Festivity Current Affairs 2026', 'Festivals India 2026 Gujarati', 'Indian Festival MCQ Gujarati', 'Festivity Quiz GPSC GSSSB', 'Cultural Events 2026 Quiz', 'National Celebration Gujarati'],
    gujaratiKeywords: ['તહેવાર કરંટ અફેર્સ', 'ભારત ઉત્સવ MCQ ગુજરાતી ૨૦૨૬'],
    exams: ['GSSSB CCE', 'GPSC Class 1-2', 'PSI', 'Constable'],
    faqs: [
      { q: 'Festivity current affairs in Gujarati ક્યાં practice કરવું?', a: 'CurrentAdda Festivity category page par Indian festivals, national celebrations MCQs Gujarati explanations sathe practice karo.' },
    ],
    relatedCategories: ['Important Days', 'Art and Culture', 'National'],
    color: 'fuchsia', emoji: '🎉',
  },
  'Finance': {
    name: 'Finance', gujaratiName: 'ફાઇનાન્સ', slug: 'Finance',
    shortDesc: 'Finance Current Affairs in Gujarati — Budget, Stock Market, Insurance, Tax 2026.',
    longDesc: 'Finance current affairs cover the Union Budget, stock market milestones, insurance reforms, tax policy changes, mutual funds, SEBI regulations, and India\'s fiscal deficit. Tested in GPSC and GSSSB CCE exams.',
    gujaratiDesc: 'Union Budget, Stock Market, Insurance, Tax Policy, SEBI, Mutual Funds. GPSC, GSSSB CCE, PSI, Talati, Constable exams.',
    keywords: ['Finance Current Affairs 2026', 'Finance Current Affairs in Gujarati', 'Budget 2026 Quiz Gujarati', 'Finance MCQ GPSC', 'Stock Market Current Affairs Gujarati', 'SEBI MCQ 2026', 'Tax Policy India 2026'],
    gujaratiKeywords: ['ફાઇનાન્સ કરંટ અફેર્સ', 'Budget MCQ ગુજરાતી ૨૦૨૬', 'Stock Market ક્વિઝ ગુજરાતી'],
    exams: ['GPSC Class 1-2', 'GSSSB CCE', 'PSI', 'Talati'],
    faqs: [
      { q: 'Finance current affairs in Gujarati ક્યાં practice કરવું?', a: 'CurrentAdda Finance category page par Budget, Stock Market, SEBI MCQs Gujarati explanations sathe practice karo.' },
    ],
    relatedCategories: ['Economy', 'Banking', 'Business'],
    color: 'emerald', emoji: '💰',
  },
  'Important Days': {
    name: 'Important Days', gujaratiName: 'મહત્વના દિવસો', slug: 'Important Days',
    shortDesc: 'Important Days Current Affairs in Gujarati — National & International Days 2026.',
    longDesc: 'Important Days MCQs cover National Days (Republic Day, Independence Day), International Days (Earth Day, World Health Day), and UN commemorations. This is the most frequently tested topic in all Gujarat competitive exams — every exam has 2-5 questions from Important Days.',
    gujaratiDesc: 'National Days, International Days, UN Days — Republic Day, Independence Day, World Health Day. GPSC, GSSSB CCE, PSI, Constable, Talati — બધા exams.',
    keywords: ['Important Days Current Affairs 2026', 'Important Days in Gujarati', 'National Days MCQ Gujarati', 'Important Days Quiz GPSC GSSSB', 'International Days 2026 Gujarati', 'UN Days 2026 Gujarati Quiz'],
    gujaratiKeywords: ['મહત્વના દિવસો ૨૦૨૬', 'Important Days MCQ ગુજરાતી', 'રાષ્ટ્રીય દિવસ ક્વિઝ ગુજરાતી'],
    exams: ['GPSC Class 1-2', 'GSSSB CCE', 'PSI', 'Constable', 'Talati', 'Bin Sachivalay'],
    faqs: [
      { q: 'Important Days current affairs in Gujarati ક્યાં practice કરવું?', a: 'CurrentAdda Important Days category page par National, International days MCQs Gujarati explanations sathe practice karo.' },
      { q: 'How many important days questions come in GSSSB CCE 2026?', a: 'GSSSB CCE typically has 3-5 questions on Important Days. This is one of the most asked topics across all Gujarat government exams.' },
    ],
    relatedCategories: ['National', 'International', 'Festivity'],
    color: 'rose', emoji: '📅',
  },
  'International': {
    name: 'International', gujaratiName: 'આંતરરાષ્ટ્રીય', slug: 'International',
    shortDesc: 'International Current Affairs in Gujarati — World Events, UN, G20, Diplomacy 2026.',
    longDesc: 'International current affairs cover UN resolutions, G7/G20 summits, world leaders, bilateral agreements between India and other countries, international organizations, global conflicts, and foreign policy. Important for GPSC and GSSSB CCE.',
    gujaratiDesc: 'UN, G20, G7, World Leaders, International Organizations, India Foreign Policy. GPSC, GSSSB CCE, PSI, Constable, Talati exams.',
    keywords: ['International Current Affairs 2026', 'International Current Affairs in Gujarati', 'World Events MCQ Gujarati', 'International Quiz GPSC', 'UN G20 Current Affairs Gujarati', 'India Foreign Policy 2026 Quiz', 'World Affairs Gujarati 2026'],
    gujaratiKeywords: ['આંતરરાષ્ટ્રીય કરંટ અફેર્સ', 'International MCQ ગુજરાતી ૨૦૨૬', 'World Events ક્વિઝ ગુજરાતી'],
    exams: ['GPSC Class 1-2', 'GSSSB CCE', 'PSI', 'Constable', 'Talati'],
    faqs: [
      { q: 'International current affairs in Gujarati ક્યાં practice કરવું?', a: 'CurrentAdda International category page par UN, G20, World Leaders MCQs Gujarati explanations sathe practice karo.' },
      { q: 'Which international topics are important for GPSC exam?', a: 'UN summits, G20/G7 conferences, India bilateral agreements, international organization heads, and global peace initiatives are key GPSC topics.' },
    ],
    relatedCategories: ['National', 'Defence', 'Politics'],
    color: 'blue', emoji: '🌍',
  },
  'National': {
    name: 'National', gujaratiName: 'રાષ્ટ્રીય', slug: 'National',
    shortDesc: 'National Current Affairs in Gujarati — India News, Government Schemes, Modi 2026.',
    longDesc: 'National current affairs are the backbone of every Gujarat competitive exam. Topics include Government of India schemes, Parliament sessions, President/PM decisions, national infrastructure, and major domestic events. Practice 300+ National MCQs in Gujarati.',
    gujaratiDesc: 'ભારત સરકાર, PM Modi, Schemes, Parliament, Infrastructure, National Events. GPSC, GSSSB CCE, PSI, Constable, Talati, Bin Sachivalay exams.',
    keywords: ['National Current Affairs 2026', 'National Current Affairs in Gujarati', 'India Current Affairs Gujarati 2026', 'National MCQ GPSC GSSSB', 'Government Schemes 2026 Gujarat', 'Modi Schemes 2026 Gujarati', 'India News MCQ Gujarati'],
    gujaratiKeywords: ['રાષ્ટ્રીય કરંટ અફેર્સ ૨૦૨૬', 'ભારત સમાચાર MCQ ગુજરાતી', 'National ક્વિઝ GPSC GSSSB'],
    exams: ['GPSC Class 1-2', 'GSSSB CCE', 'PSI', 'Constable', 'Talati', 'Bin Sachivalay'],
    faqs: [
      { q: 'National current affairs in Gujarati ક્યાં practice કરવું?', a: 'CurrentAdda National category par 300+ MCQs Gujarati explanations sathe practice karo. Daily update thay che.' },
      { q: 'National current affairs 2026 — GSSSB CCE mate top topics?', a: 'Government schemes, Parliament news, national awards, infrastructure projects, and PM/President decisions are top National topics for GSSSB CCE 2026.' },
    ],
    relatedCategories: ['Politics', 'Economy', 'International'],
    color: 'indigo', emoji: '🇮🇳',
  },
  'Obituary': {
    name: 'Obituary', gujaratiName: 'નિધન', slug: 'Obituary',
    shortDesc: 'Obituary Current Affairs in Gujarati — Notable Deaths, Last Known For 2026.',
    longDesc: 'Obituary current affairs cover notable personalities who passed away, their achievements, contributions, and what they were known for. This topic always appears in GPSC and GSSSB CCE exams — 1-2 questions guaranteed.',
    gujaratiDesc: 'Notable Personalities Deaths, Awards, Contributions. GPSC, GSSSB CCE, PSI, Constable, Talati exams.',
    keywords: ['Obituary Current Affairs 2026', 'Obituary Current Affairs in Gujarati', 'Deaths MCQ Gujarati', 'Obituary Quiz GPSC GSSSB', 'Notable Deaths 2026 India Gujarati'],
    gujaratiKeywords: ['નિધન કરંટ અફેર્સ', 'Obituary MCQ ગુજરાતી ૨૦૨૬'],
    exams: ['GPSC Class 1-2', 'GSSSB CCE', 'PSI', 'Constable', 'Talati'],
    faqs: [
      { q: 'Obituary current affairs in Gujarati ક્યાં practice કરવું?', a: 'CurrentAdda Obituary category page par Notable Deaths MCQs Gujarati explanations sathe practice karo.' },
    ],
    relatedCategories: ['Persons', 'National', 'Awards and Honours'],
    color: 'slate', emoji: '🕊️',
  },
  'Persons': {
    name: 'Persons', gujaratiName: 'વ્યક્તિઓ', slug: 'Persons',
    shortDesc: 'Persons Current Affairs in Gujarati — New Appointments, CEO, Chief Ministers 2026.',
    longDesc: 'Persons current affairs cover new government appointments, Chief Ministers, Governors, heads of institutions (RBI Governor, CBI Director, CAG), diplomatic appointments, and corporate CEO changes. One of the most asked topics in Gujarat exams.',
    gujaratiDesc: 'CM, Governor, RBI/CBI Chief, Diplomat Appointments, CEO Changes. GPSC, GSSSB CCE, PSI, Constable, Talati exams.',
    keywords: ['Persons Current Affairs 2026', 'Persons Current Affairs in Gujarati', 'Appointments 2026 Gujarati', 'Persons MCQ GPSC GSSSB', 'New Appointments India 2026 Quiz', 'CM Governor Appointments 2026'],
    gujaratiKeywords: ['વ્યક્તિઓ કરંટ અફેર્સ', 'નિમણૂક MCQ ગુજરાતી ૨૦૨૬', 'Persons ક્વિઝ GPSC GSSSB'],
    exams: ['GPSC Class 1-2', 'GSSSB CCE', 'PSI', 'Constable', 'Talati'],
    faqs: [
      { q: 'Persons current affairs in Gujarati ક્યાં practice કરવું?', a: 'CurrentAdda Persons category page par Appointments, CM, RBI Governor MCQs Gujarati explanations sathe practice karo.' },
      { q: 'Appointment related current affairs — GSSSB CCE mate?', a: 'RBI Governor, CBI Director, Army Chief, CM/Governor appointments, and major institutional head changes are most asked in GSSSB CCE.' },
    ],
    relatedCategories: ['National', 'Politics', 'Awards and Honours'],
    color: 'violet', emoji: '👤',
  },
  'Places': {
    name: 'Places', gujaratiName: 'સ્થળો', slug: 'Places',
    shortDesc: 'Places Current Affairs in Gujarati — New Discoveries, UNESCO Sites, Summits 2026.',
    longDesc: 'Places current affairs include new UNESCO World Heritage Sites, summit locations, conference host cities, new national parks, and geography-based current events. Tested across all Gujarat government exams.',
    gujaratiDesc: 'UNESCO Heritage Sites, Summit Locations, National Parks, Conference Cities. GPSC, GSSSB CCE, PSI, Talati exams.',
    keywords: ['Places Current Affairs 2026', 'Places Current Affairs in Gujarati', 'UNESCO Sites 2026 Gujarati', 'Places MCQ GPSC GSSSB', 'Summit Location 2026 Quiz', 'New Heritage Site India 2026'],
    gujaratiKeywords: ['સ્થળો કરંટ અફેર્સ', 'UNESCO MCQ ગુજરાતી ૨૦૨૬', 'Places ક્વિઝ GPSC'],
    exams: ['GPSC Class 1-2', 'GSSSB CCE', 'PSI', 'Talati'],
    faqs: [
      { q: 'Places current affairs in Gujarati ક્યાં practice કરવું?', a: 'CurrentAdda Places category page par UNESCO, Summit Location MCQs Gujarati explanations sathe practice karo.' },
    ],
    relatedCategories: ['National', 'International', 'Environment'],
    color: 'rose', emoji: '📍',
  },
  'Politics': {
    name: 'Politics', gujaratiName: 'રાજકારણ', slug: 'Politics',
    shortDesc: 'Politics Current Affairs in Gujarati — Elections, Parliament, State Politics 2026.',
    longDesc: 'Politics current affairs cover Election results, state and national political developments, new party formations, election commission decisions, and political appointments. Important for GPSC and GSSSB CCE, though carefully balanced without party bias.',
    gujaratiDesc: 'Election Results, Parliament Sessions, State Politics, Political Developments. GPSC, GSSSB CCE, PSI, Talati exams.',
    keywords: ['Politics Current Affairs 2026', 'Politics Current Affairs in Gujarati', 'Elections 2026 Gujarat MCQ', 'Politics Quiz GPSC', 'Parliament Politics 2026 Gujarati', 'State Politics MCQ GSSSB'],
    gujaratiKeywords: ['રાજકારણ કરંટ અફેર્સ', 'Election MCQ ગુજરાતી ૨૦૨૬', 'Politics ક્વિઝ GPSC GSSSB'],
    exams: ['GPSC Class 1-2', 'GSSSB CCE', 'PSI', 'Talati'],
    faqs: [
      { q: 'Politics current affairs in Gujarati ક્યાં practice કરવું?', a: 'CurrentAdda Politics category page par Election, Parliament MCQs Gujarati explanations sathe practice karo.' },
    ],
    relatedCategories: ['National', 'Bills and Acts', 'Persons'],
    color: 'blue', emoji: '🗳️',
  },
  'Science': {
    name: 'Science', gujaratiName: 'વિજ્ઞાન', slug: 'Science',
    shortDesc: 'Science Current Affairs in Gujarati — ISRO, Space, Medical Research, DRDO 2026.',
    longDesc: 'Science current affairs cover ISRO missions, space exploration, medical discoveries, Nobel Prize in Science, DRDO innovations, biotechnology, and scientific policies. One of the highest-yielding topics in GPSC and GSSSB CCE exams.',
    gujaratiDesc: 'ISRO Missions, Space, Medical Research, DRDO, Nobel Science Prize. GPSC, GSSSB CCE, PSI, Constable, Talati exams.',
    keywords: ['Science Current Affairs 2026', 'Science Current Affairs in Gujarati', 'ISRO 2026 Current Affairs Gujarati', 'Science MCQ GPSC GSSSB', 'Space Mission 2026 Gujarati Quiz', 'DRDO Science 2026', 'Medical Science MCQ Gujarati'],
    gujaratiKeywords: ['વિજ્ઞાન કરંટ અફેર્સ', 'ISRO MCQ ગુજરાતી ૨૦૨૬', 'Science ક્વિઝ GPSC GSSSB'],
    exams: ['GPSC Class 1-2', 'GSSSB CCE', 'PSI', 'Constable', 'Talati'],
    faqs: [
      { q: 'Science current affairs in Gujarati ક્યાં practice કરવું?', a: 'CurrentAdda Science category page par ISRO, Medical, DRDO MCQs Gujarati explanations sathe practice karo.' },
      { q: 'Which science topics come in GPSC Class 1-2 exam?', a: 'ISRO missions, Nobel Prize in Physics/Chemistry/Medicine, DRDO innovations, and major scientific discoveries are frequently asked in GPSC.' },
    ],
    relatedCategories: ['Technology', 'Defence', 'Education'],
    color: 'purple', emoji: '🔬',
  },
  'Sports': {
    name: 'Sports', gujaratiName: 'રમત-ગમત', gujaratiName2: 'સ્પોર્ટ્સ', slug: 'Sports',
    shortDesc: 'Sports Current Affairs in Gujarati — IPL, Olympics, Cricket, Asian Games 2026.',
    longDesc: 'Sports current affairs are the most popular category in exam preparation. Topics include ICC Cricket tournaments, IPL records, Olympics, Asian Games, Commonwealth Games, new sports world records, and Gujarat sports achievements. Must-practice for all Gujarat exams.',
    gujaratiDesc: 'Cricket, IPL, Olympics, Asian Games, Commonwealth Games, World Records. GPSC, GSSSB CCE, PSI, Constable, Talati — બધા exams.',
    keywords: ['Sports Current Affairs 2026', 'Sports Current Affairs in Gujarati', 'Cricket Current Affairs Gujarati', 'Sports MCQ GPSC GSSSB', 'IPL 2026 Current Affairs Gujarati', 'Olympics 2026 Gujarati Quiz', 'Asian Games Current Affairs'],
    gujaratiKeywords: ['રમત-ગમત કરંટ અફેર્સ', 'Sports MCQ ગુજરાતી ૨૦૨૬', 'Cricket ક્વિઝ ગુજરાતી', 'IPL MCQ GPSC'],
    exams: ['GPSC Class 1-2', 'GSSSB CCE', 'PSI', 'Constable', 'Talati', 'Bin Sachivalay'],
    faqs: [
      { q: 'Sports current affairs in Gujarati ક્યાં practice કરવું?', a: 'CurrentAdda Sports category page par Cricket, IPL, Olympics MCQs Gujarati explanations sathe practice karo.' },
      { q: 'Sports current affairs 2026 — GSSSB CCE mate top topics?', a: 'IPL records, ICC tournaments, Olympic medals, Asian Games results, and world sports records are top sports topics in GSSSB CCE 2026.' },
    ],
    relatedCategories: ['Awards and Honours', 'Persons', 'National'],
    color: 'orange', emoji: '🏅',
  },
  'State': {
    name: 'State', gujaratiName: 'રાજ્ય', slug: 'State',
    shortDesc: 'State Current Affairs in Gujarati — Gujarat & All India State News 2026.',
    longDesc: 'State current affairs cover Gujarat and all Indian state news — new state capitals, state government schemes, CM/Governor appointments, state infrastructure, and state-level competitive exam news. High importance for all Gujarat government exams.',
    gujaratiDesc: 'Gujarat + All States Current Affairs. State Schemes, CM, Governor, Infrastructure. GPSC, GSSSB CCE, PSI, Talati exams.',
    keywords: ['State Current Affairs 2026', 'State Current Affairs in Gujarati', 'Gujarat Current Affairs 2026', 'State MCQ GPSC GSSSB', 'Gujarat State Schemes 2026', 'Indian States Current Affairs Gujarati', 'State News Gujarat MCQ'],
    gujaratiKeywords: ['રાજ્ય કરંટ અફેર્સ ૨૦૨૬', 'Gujarat Current Affairs ગુજરાતી', 'State MCQ GPSC GSSSB'],
    exams: ['GPSC Class 1-2', 'GSSSB CCE', 'PSI', 'Constable', 'Talati'],
    faqs: [
      { q: 'State current affairs in Gujarati ક્યાં practice કરવું?', a: 'CurrentAdda State category page par Gujarat & India State MCQs Gujarati explanations sathe practice karo.' },
    ],
    relatedCategories: ['National', 'Politics', 'Persons'],
    color: 'emerald', emoji: '🗺️',
  },
  'Talkies': {
    name: 'Talkies', gujaratiName: 'ફિલ્મ', gujaratiName2: 'સિનેમા', slug: 'Talkies',
    shortDesc: 'Talkies (Film) Current Affairs in Gujarati — Oscar, Filmfare, Bollywood 2026.',
    longDesc: 'Talkies current affairs cover Oscar awards, Filmfare, National Film Awards, Bollywood and regional film milestones, OTT platform news, and box office records. Appears in GSSSB CCE Cultural section.',
    gujaratiDesc: 'Oscar, Filmfare, National Film Awards, Bollywood, OTT. GSSSB CCE, GPSC, PSI exams.',
    keywords: ['Talkies Current Affairs 2026', 'Film Current Affairs in Gujarati', 'Oscar 2026 Gujarati Quiz', 'Bollywood Current Affairs MCQ', 'Filmfare Awards 2026 Gujarati', 'National Film Award 2026 Quiz'],
    gujaratiKeywords: ['ફિલ્મ કરંટ અફેર્સ ગુજરાતી', 'Oscar MCQ ૨૦૨૬', 'Talkies ક્વિઝ GPSC'],
    exams: ['GSSSB CCE', 'GPSC Class 1-2', 'PSI'],
    faqs: [
      { q: 'Talkies current affairs in Gujarati ક્યાં practice કરવું?', a: 'CurrentAdda Talkies category page par Oscar, Filmfare, National Film Awards MCQs Gujarati explanations sathe practice karo.' },
    ],
    relatedCategories: ['Art and Culture', 'Awards and Honours', 'Festivity'],
    color: 'pink', emoji: '🎬',
  },
  'Technology': {
    name: 'Technology', gujaratiName: 'ટેક્નોલોજી', slug: 'Technology',
    shortDesc: 'Technology Current Affairs in Gujarati — AI, Space, Cyber, Digital India 2026.',
    longDesc: 'Technology current affairs cover AI developments, new tech policies, Digital India updates, cybersecurity, 5G rollout, satellite launches, and tech company news. Increasingly asked in GPSC and GSSSB CCE exams.',
    gujaratiDesc: 'AI, Digital India, Cybersecurity, 5G, Satellite, Tech Policy. GPSC, GSSSB CCE, PSI, Bin Sachivalay exams.',
    keywords: ['Technology Current Affairs 2026', 'Technology Current Affairs in Gujarati', 'AI Current Affairs Gujarati', 'Technology MCQ GPSC GSSSB', 'Digital India 2026 Quiz', '5G Current Affairs Gujarati', 'Cybersecurity MCQ Gujarat'],
    gujaratiKeywords: ['ટેક્નોલોજી કરંટ અફેર્સ', 'AI MCQ ગુજરાતી ૨૦૨૬', 'Technology ક્વિઝ GPSC'],
    exams: ['GPSC Class 1-2', 'GSSSB CCE', 'PSI', 'Bin Sachivalay'],
    faqs: [
      { q: 'Technology current affairs in Gujarati ક્યાં practice કરવું?', a: 'CurrentAdda Technology category page par AI, Digital India, 5G MCQs Gujarati explanations sathe practice karo.' },
    ],
    relatedCategories: ['Science', 'Education', 'National'],
    color: 'slate', emoji: '💻',
  },
  'Miscellaneous': {
    name: 'Miscellaneous', gujaratiName: 'વિવિધ', slug: 'Miscellaneous',
    shortDesc: 'Miscellaneous Current Affairs in Gujarati — Mixed Topics, GK 2026.',
    longDesc: 'Miscellaneous current affairs include all topics that don\'t fit a single category — mixed General Knowledge, unusual records, curious current events, and diverse exam-relevant topics. Good for General Awareness rounds.',
    gujaratiDesc: 'Mixed GK, Unusual Records, Diverse Topics. GPSC, GSSSB CCE, PSI, Constable, Talati exams.',
    keywords: ['Miscellaneous Current Affairs 2026', 'Miscellaneous Current Affairs in Gujarati', 'General Knowledge MCQ Gujarati', 'Miscellaneous Quiz GPSC GSSSB', 'GK Current Affairs 2026 Gujarati'],
    gujaratiKeywords: ['વિવિધ કરંટ અફેર્સ', 'General Knowledge MCQ ગુજરાતી ૨૦૨૬', 'Miscellaneous ક્વિઝ GPSC'],
    exams: ['GPSC Class 1-2', 'GSSSB CCE', 'PSI', 'Constable', 'Talati'],
    faqs: [
      { q: 'Miscellaneous current affairs in Gujarati ક્યાં practice કરવું?', a: 'CurrentAdda Miscellaneous category page par Mixed GK MCQs Gujarati explanations sathe practice karo.' },
    ],
    relatedCategories: ['National', 'International', 'Science'],
    color: 'slate', emoji: '🗂️',
  },
};

export function getCategorySeo(category: string): CategorySeoData | null {
  return CATEGORY_SEO[category] || null;
}

export const ALL_CATEGORY_NAMES = Object.keys(CATEGORY_SEO);
