/**
 * Reel Frame Screenshot Generator using Playwright
 * Takes the HTML generated by ReelGenerator and creates 1080x1920 PNG frames.
 *
 * Usage: node generate_reel_frames.js <html_path> <output_dir>
 */

const playwright = require('playwright');
const fs = require('fs');
const path = require('path');

async function generateReelFrames(htmlPath, outputDir) {
    console.log('🎬 Starting Reel Frame generation with Playwright...');

    let browser;
    try {
        const absoluteHtmlPath = path.resolve(htmlPath);
        const htmlUrl = `file://${absoluteHtmlPath}`;
        console.log(`✓ HTML file URL: ${htmlUrl}`);

        browser = await playwright.chromium.launch({
            headless: true,
            args: [
                '--no-sandbox',
                '--disable-setuid-sandbox',
                '--disable-dev-shm-usage',
                '--font-render-hinting=none',
            ]
        });
        console.log('✓ Browser launched');

        // 9:16 vertical viewport for Reels — with 2x device scale for crisp output
        const page = await browser.newPage({
            deviceScaleFactor: 2,
            viewport: { width: 1200, height: 2100 }
        });

        await page.goto(htmlUrl, {
            waitUntil: 'load',
            timeout: 60000
        });
        console.log('✓ HTML content loaded');

        // Wait for fonts to settle
        await page.waitForTimeout(4000);
        console.log('✓ Fonts loaded');

        // Find all reel frames
        const frames = await page.$$('.reel-frame');
        console.log(`✓ Found ${frames.length} reel frames to capture...`);

        // Build ordered list — we need specific naming for FFmpeg concat
        const frameData = [];
        for (let i = 0; i < frames.length; i++) {
            const frame = frames[i];
            const id = await frame.evaluate(el => el.id);

            const framePath = path.join(outputDir, `${id}.png`);

            await frame.screenshot({
                path: framePath,
                type: 'png'
            });

            frameData.push({ id, path: framePath });
            console.log(`  📸 Saved ${id}.png`);
        }

        // Generate frame list JSON for the video builder
        const manifestPath = path.join(outputDir, 'frames_manifest.json');
        fs.writeFileSync(manifestPath, JSON.stringify(frameData, null, 2));
        console.log(`\n✓ Frame manifest saved: ${manifestPath}`);

        console.log(`\n✅ SUCCESS! All ${frames.length} reel frames saved to: ${outputDir}`);

    } catch (error) {
        console.error(`✗ Reel Frame Generation failed: ${error.stack || error.message}`);
        process.exit(1);
    } finally {
        if (browser) {
            await browser.close();
        }
    }
}

// ── Main ──
const htmlPath = process.argv[2];
if (!htmlPath) {
    console.error("❌ Please provide the path to the reel HTML file as the first argument.");
    console.log("Example: node generate_reel_frames.js output/reel_0_2026.html output_reels/20260228/");
    process.exit(1);
}

const outputDir = process.argv[3] || path.join(__dirname, 'output_reels', 'frames');

if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
}

generateReelFrames(htmlPath, outputDir).catch(err => {
    console.error(`✗ Fatal error: ${err.stack || err.message}`);
    process.exit(1);
});
