/**
 * Beautiful Image Generator using Playwright
 * Takes the HTML generated by ImageGenerator and creates 1080x1080 images for each question.
 */

import { chromium } from 'playwright';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

async function generateImages(htmlPath, outputDir) {
    console.log('🚀 Starting Image generation with Playwright...');

    try {
        // Read HTML file
        const htmlContent = fs.readFileSync(htmlPath, 'utf-8');
        console.log('✓ HTML file loaded');

        // Launch browser
        const browser = await chromium.launch({
            headless: true
        });
        console.log('✓ Browser launched');

        // Create page with high device scale factor for crisp Retina/4K images
        // Instagram loves 1080x1080 but scale 2 gives 2160x2160 which compresses nicely
        const page = await browser.newPage({
            deviceScaleFactor: 2,
            viewport: { width: 1200, height: 1200 } // Big enough to fit the cards
        });

        // Set content
        await page.setContent(htmlContent, {
            waitUntil: 'networkidle'
        });
        console.log('✓ HTML content loaded');

        // Wait for fonts to load properly
        await page.evaluate(() => document.fonts.ready);
        console.log('✓ Fonts loaded');

        // Find all cards
        const cards = await page.$$('.instagram-card');
        console.log(`✓ Found ${cards.length} image cards to process...`);

        for (let i = 0; i < cards.length; i++) {
            const card = cards[i];
            const id = await card.evaluate(el => el.id); // e.g., q1_card1, q1_card2

            const cardPath = path.join(outputDir, `${id}.png`);

            // Only capture the bounding box of the card itself
            await card.screenshot({
                path: cardPath,
                type: 'png'
            });

            console.log(`  📸 Saved ${id}.png (1080x1080 Retina)`);
        }

        await browser.close();
        console.log('✓ Browser closed');

        console.log(`\n✅ SUCCESS! All images beautifully formatted and saved to: ${outputDir}`);

    } catch (error) {
        console.error('❌ Error generating images:', error);
        throw error;
    }
}

// Main execution
const htmlPath = process.argv[2];
if (!htmlPath) {
    console.error("❌ Please provide the path to the HTML file as the first argument.");
    console.log("Example: node generate_images.js output/images_quiz_2026.html");
    process.exit(1);
}

// Create a date-based output directory
const dateStr = new Date().toISOString().split('T')[0];
const outputDir = process.argv[3] || path.join(__dirname, 'output_images', dateStr);

// Ensure output directory exists
if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
}

generateImages(htmlPath, outputDir)
    .then(() => {
        console.log('\n🎉 Image generation complete!');
        process.exit(0);
    })
    .catch((error) => {
        console.error('\n💥 Image generation failed:', error.message);
        process.exit(1);
    });
