/**
 * Beautiful Image Generator using Playwright
 * Takes the HTML generated by ImageGenerator and creates 1080x1080 images for each question.
 */

const playwright = require('playwright');
const fs = require('fs');
const path = require('path');

async function generateImages(htmlPath, outputDir) {
    console.log('🚀 Starting Image generation with Playwright...');

    let browser;
    try {
        // Read HTML file - convert relative to absolute
        const absoluteHtmlPath = path.resolve(htmlPath);
        const htmlUrl = `file://${absoluteHtmlPath}`;
        console.log(`✓ HTML file URL: ${htmlUrl}`);

        // Launch browser
        browser = await playwright.chromium.launch({
            headless: true,
            args: [
                '--no-sandbox',
                '--disable-setuid-sandbox',
                '--disable-dev-shm-usage',
                '--font-render-hinting=none',
            ]
        });
        console.log('✓ Browser launched');

        // Create page with high device scale factor for crisp Retina/4K images
        const page = await browser.newPage({
            deviceScaleFactor: 2,
            viewport: { width: 1200, height: 1200 }
        });

        // Load content via file URL (same approach as generate_pdf.js)
        await page.goto(htmlUrl, {
            waitUntil: 'load',
            timeout: 60000
        });
        console.log('✓ HTML content loaded');

        // Wait for fonts and Tailwind to settle
        await page.waitForTimeout(3000);
        console.log('✓ Fonts loaded');

        // Find all cards
        const cards = await page.$$('.instagram-card');
        console.log(`✓ Found ${cards.length} image cards to process...`);

        for (let i = 0; i < cards.length; i++) {
            const card = cards[i];
            const id = await card.evaluate(el => el.id);

            const cardPath = path.join(outputDir, `${id}.png`);

            await card.screenshot({
                path: cardPath,
                type: 'png'
            });

            console.log(`  📸 Saved ${id}.png`);
        }

        console.log(`\n✅ SUCCESS! All ${cards.length} images saved to: ${outputDir}`);

    } catch (error) {
        console.error(`✗ Image Generation failed: ${error.stack || error.message}`);
        process.exit(1);
    } finally {
        if (browser) {
            await browser.close();
        }
    }
}

// Main execution
const htmlPath = process.argv[2];
if (!htmlPath) {
    console.error("❌ Please provide the path to the HTML file as the first argument.");
    console.log("Example: node generate_images.js output/images_quiz_2026.html");
    process.exit(1);
}

// Create a date-based output directory
const dateStr = new Date().toISOString().split('T')[0];
const outputDir = process.argv[3] || path.join(__dirname, 'output_images', dateStr);

// Ensure output directory exists
if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
}

generateImages(htmlPath, outputDir).catch(err => {
    console.error(`✗ Fatal error: ${err.stack || err.message}`);
    process.exit(1);
});
